Repository hanwha-be09-4vengers/Yoribogo, pull requests merged in 2024-10, with the labels that each got.

#2 Feat: 결과 카드 뒤집기 기능 추가
  client/src/components/ResultBoard.vue
  client/src/views/ResultView.vue
Labels: enhancement

#12 Refactor: 모델링 변경
  db_modeling/yoribogo_modeling.damx
Labels: enhancement

#30 Refactor: 데이터베이스 id, 비번 yoribogo로 변경
  db_queries/public_recipe_script.py
Labels: enhancement

#31 Feat: 요리 레시피 페이지별 조회 구현
  server/src/main/java/com/avengers/yoribogo/common/exception/ErrorCode.java
  server/src/main/java/com/avengers/yoribogo/recipe/controller/RecipeController.java
  server/src/main/java/com/avengers/yoribogo/recipe/domain/MenuType.java
  server/src/main/java/com/avengers/yoribogo/recipe/domain/Recipe.java
  server/src/main/java/com/avengers/yoribogo/recipe/dto/RecipeDTO.java
  server/src/main/java/com/avengers/yoribogo/recipe/repository/RecipeRepository.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeService.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeServiceImpl.java
  server/src/test/java/com/avengers/yoribogo/recipe/service/RecipeServiceTests.java
Labels: enhancement

#32 Feat: 요리 레시피 단건 조회 구현
  server/src/main/java/com/avengers/yoribogo/recipe/controller/RecipeController.java
  server/src/main/java/com/avengers/yoribogo/recipe/domain/Recipe.java
  server/src/main/java/com/avengers/yoribogo/recipe/dto/RecipeDTO.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeService.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeServiceImpl.java
  server/src/test/java/com/avengers/yoribogo/recipe/service/RecipeServiceTests.java
Labels: enhancement

#33 Feat: 요리 레시피 요리 이름으로 조회 구현
  server/src/main/java/com/avengers/yoribogo/recipe/controller/RecipeController.java
  server/src/main/java/com/avengers/yoribogo/recipe/repository/RecipeRepository.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeService.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeServiceImpl.java
  server/src/test/java/com/avengers/yoribogo/recipe/service/RecipeServiceTests.java
Labels: enhancement

#34 Feat: 요리 레시피 수정 구현
  server/src/main/java/com/avengers/yoribogo/recipe/controller/RecipeController.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeService.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeServiceImpl.java
  server/src/test/java/com/avengers/yoribogo/recipe/service/RecipeServiceTests.java
Labels: enhancement

#35 Feat: 요리 레시피 삭제 구현
  db_queries/table_definition.sql
  server/src/main/java/com/avengers/yoribogo/recipe/controller/RecipeController.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeService.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeServiceImpl.java
  server/src/test/java/com/avengers/yoribogo/recipe/service/RecipeServiceTests.java
Labels: enhancement

#37 Feat: 요리 레시피 등록 구현
  db_queries/integrated_data_insert.sql
  server/src/main/java/com/avengers/yoribogo/recipe/controller/RecipeController.java
  server/src/main/java/com/avengers/yoribogo/recipe/domain/AIRecipe.java
  server/src/main/java/com/avengers/yoribogo/recipe/domain/PublicDataRecipe.java
  server/src/main/java/com/avengers/yoribogo/recipe/dto/AIRecipeDTO.java
  server/src/main/java/com/avengers/yoribogo/recipe/dto/PublicDataRecipeDTO.java
  server/src/main/java/com/avengers/yoribogo/recipe/repository/AIRecipeRepository.java
  server/src/main/java/com/avengers/yoribogo/recipe/repository/PublicDataRecipeRepository.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeService.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeServiceImpl.java
  server/src/test/java/com/avengers/yoribogo/recipe/service/RecipeServiceTests.java
Labels: enhancement

#38 Feat: 추천 요리 회원별 조회
  server/src/main/java/com/avengers/yoribogo/recipe/controller/RecommendedMenuController.java
  server/src/main/java/com/avengers/yoribogo/recipe/domain/RecommendedMenu.java
  server/src/main/java/com/avengers/yoribogo/recipe/domain/RecommendedMenuStatus.java
  server/src/main/java/com/avengers/yoribogo/recipe/domain/Satisfaction.java
  server/src/main/java/com/avengers/yoribogo/recipe/dto/GoodMenuDTO.java
  server/src/main/java/com/avengers/yoribogo/recipe/dto/RecommendedMenuDTO.java
  server/src/main/java/com/avengers/yoribogo/recipe/repository/RecommendedMenuRepository.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/AIRecipeService.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/AIRecipeServiceImpl.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/PublicDataRecipeService.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/PublicDataRecipeServiceImpl.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeServiceImpl.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecommendedMenuService.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecommendedMenuServiceImpl.java
  server/src/test/java/com/avengers/yoribogo/recipe/service/RecommendedMenuServiceTests.java
Labels: enhancement

#39 Feat: 추천 요리 삭제 구현
  server/src/main/java/com/avengers/yoribogo/recipe/controller/RecipeController.java
  server/src/main/java/com/avengers/yoribogo/recipe/controller/RecommendedMenuController.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecommendedMenuService.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecommendedMenuServiceImpl.java
  server/src/test/java/com/avengers/yoribogo/recipe/service/RecommendedMenuServiceTests.java
Labels: enhancement

#58 Feat: 요리 추천 결과 보여주기 구현
  client/package-lock.json
  client/package.json
  client/src/assets/bibimbap.svg
  client/src/assets/cloudy.svg
  client/src/assets/main.css
  client/src/assets/sunny.svg
  client/src/components/CardBoard.vue
  client/src/components/Loading.vue
  client/src/components/QuestionNav.vue
  client/src/components/ResultBoard.vue
  client/src/views/QuestionView.vue
  client/src/views/ResultView.vue
  client/vite.config.js
Labels: enhancement

#59 feat: 나만의 레시피 등록
  server/src/main/java/com/avengers/yoribogo/recipeboard/controller/RecipeBoardController.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/domain/RecipeBoard.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/domain/RecipeBoardStatus.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/dto/RecipeBoardDTO.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/repository/RecipeBoardRepository.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardService.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardServiceImpl.java
Labels: enhancement

#62 Feat: 홈버튼 컴포넌트 추가
  client/src/assets/main.css
  client/src/components/HomeButton.vue
  client/src/components/MainNav.vue
  client/src/components/ResultNav.vue
  client/src/router/router.js
  client/src/views/HomeView.vue
  client/src/views/WikiView.vue
Labels: enhancement

#65 feat: 나만의 레시피 조회
  server/src/main/java/com/avengers/yoribogo/recipeboard/controller/RecipeBoardController.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardService.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardServiceImpl.java
Labels: enhancement

#69 Enum 추가
  server/src/main/java/com/avengers/yoribogo/answer/domain/Answer.java
  server/src/main/java/com/avengers/yoribogo/answer/dto/AnswerDTO.java
  server/src/main/java/com/avengers/yoribogo/common/Role.java
  server/src/main/java/com/avengers/yoribogo/common/Status.java
  server/src/main/java/com/avengers/yoribogo/inquiry/domain/Inquiry.java
  server/src/main/java/com/avengers/yoribogo/inquiry/dto/InquiryDTO.java
  server/src/main/java/com/avengers/yoribogo/inquiry/dto/InquiryOnlyDTO.java
Labels: enhancement

#70 Docs: 패키지 이름 수정
  server/src/main/java/com/avengers/yoribogo/recipeboard/controller/RecipeBoardController.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/controller/RecipeBoardManualController.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/domain/RecipeBoard.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/domain/RecipeBoardManual.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/domain/RecipeBoardStatus.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/dto/RecipeBoardDTO.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/dto/RecipeBoardManualDTO.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/repository/RecipeBoardManualRepository.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/repository/RecipeBoardRepository.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardManualService.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardManualServiceImpl.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardService.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardServiceImpl.java
Labels: documentation

#71 Docs: 오타 수정
  server/src/main/java/com/avengers/yoribogo/inquiry/service/InquiryServiceImpl.java
Labels: documentation

#73 이메일 인증 기능 추가
  db_queries/integrated_data_insert.sql
  db_queries/public_recipe_script.py
  db_queries/table_definition.sql
  server/src/main/java/com/avengers/yoribogo/config/AppConfiguration.java
  server/src/main/java/com/avengers/yoribogo/config/MailConfig.java
  server/src/main/java/com/avengers/yoribogo/config/OpenAIConfig.java
  server/src/main/java/com/avengers/yoribogo/config/RedisConfig.java
  server/src/main/java/com/avengers/yoribogo/config/S3Config.java
  server/src/main/java/com/avengers/yoribogo/openai/service/OpenAIServiceImpl.java
  server/src/main/java/com/avengers/yoribogo/user/controller/UserController.java
  server/src/main/java/com/avengers/yoribogo/user/domain/UserEntity.java
  server/src/main/java/com/avengers/yoribogo/user/domain/enums/AcceptStatus.java
  server/src/main/java/com/avengers/yoribogo/user/domain/enums/ActiveStatus.java
  server/src/main/java/com/avengers/yoribogo/user/domain/enums/OAuthProvider.java
  server/src/main/java/com/avengers/yoribogo/user/domain/enums/SignupPath.java
  server/src/main/java/com/avengers/yoribogo/user/domain/enums/UserRole.java
  server/src/main/java/com/avengers/yoribogo/user/domain/vo/email/EmailVerificationSignupVO.java
  server/src/main/java/com/avengers/yoribogo/user/domain/vo/email/EmailVerificationVO.java
  server/src/main/java/com/avengers/yoribogo/user/domain/vo/email/ResponseEmailMessageVO.java
  server/src/main/java/com/avengers/yoribogo/user/domain/vo/kakao/KakaoAuthorizationCode.java
  server/src/main/java/com/avengers/yoribogo/user/domain/vo/kakao/KakaoUser.java
  server/src/main/java/com/avengers/yoribogo/user/domain/vo/login/AuthTokens.java
  server/src/main/java/com/avengers/yoribogo/user/domain/vo/login/RequestLoginVO.java
  server/src/main/java/com/avengers/yoribogo/user/domain/vo/login/ResponseNormalLoginVO.java
  server/src/main/java/com/avengers/yoribogo/user/domain/vo/login/ResponseOAuthLoginVO.java
  server/src/main/java/com/avengers/yoribogo/user/domain/vo/naver/NaverAuthorizationCode.java
  server/src/main/java/com/avengers/yoribogo/user/domain/vo/naver/NaverUser.java
  server/src/main/java/com/avengers/yoribogo/user/dto/RequestUpdateUserDTO.java
  server/src/main/java/com/avengers/yoribogo/user/dto/email/EmailVerificationUserIdRequestDTO.java
  server/src/main/java/com/avengers/yoribogo/user/dto/email/EmailVerificationUserPasswordRequestDTO.java
  server/src/main/java/com/avengers/yoribogo/user/repository/UserRepository.java
  server/src/main/java/com/avengers/yoribogo/user/service/EmailVerificationService.java
  server/src/main/java/com/avengers/yoribogo/user/service/OAuth2LoginService.java
  server/src/main/java/com/avengers/yoribogo/user/service/UserService.java
  server/src/main/resources/static/index.html
  yoribogo_modeling.damx
Labels: enhancement

#76 Refactor: 이미지 로딩 최적화
  client/src/components/HomeButton.vue
  client/src/components/HomeNav.vue
  client/src/components/MenuItem.vue
  client/src/components/ResultBoard.vue
  client/src/views/WikiView.vue
Labels: enhancement

#80 Feat: 프로필 버튼 구현
  client/index.html
  client/src/assets/main.css
  client/src/components/HomeButton.vue
  client/src/components/HomeNav.vue
  client/src/components/MenuItem.vue
  client/src/components/PaginationComponent.vue
  client/src/components/ProfileButton.vue
  client/src/components/SearchBar.vue
  client/src/views/MyPageView.vue
  client/src/views/QuestionView.vue
  client/src/views/RecipeBoardView.vue
  client/src/views/ResultView.vue
  client/src/views/WikiView.vue
Labels: enhancement

#78 Test: 테스트 코드 추가
  server/src/main/java/com/avengers/yoribogo/answer/service/AnswerServiceImpl.java
  server/src/main/java/com/avengers/yoribogo/inquiry/domain/Inquiry.java
  server/src/main/java/com/avengers/yoribogo/inquiry/dto/InquiryDTO.java
  server/src/main/java/com/avengers/yoribogo/inquiry/dto/InquiryOnlyDTO.java
  server/src/main/java/com/avengers/yoribogo/inquiry/repository/InquiryRepository.java
  server/src/main/java/com/avengers/yoribogo/inquiry/service/InquiryService.java
  server/src/main/java/com/avengers/yoribogo/inquiry/service/InquiryServiceImpl.java
  server/src/main/java/com/avengers/yoribogo/mainquestion/domain/MainQuestion.java
  server/src/main/java/com/avengers/yoribogo/mainquestion/dto/MainQuestionDTO.java
  server/src/test/java/com/avengers/yoribogo/answer/AnswerTests.java
  server/src/test/java/com/avengers/yoribogo/choice/ChoiceTests.java
  server/src/test/java/com/avengers/yoribogo/inquiry/InquiryTests.java
  server/src/test/java/com/avengers/yoribogo/mainquestion/MainQuestionTests.java
Labels: enhancement

#83 Feat:나만의레시피 댓글 기능
  .idea/.gitignore
  .idea/Yoribogo.iml
  .idea/compiler.xml
  .idea/dataSources.xml
  .idea/gradle.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/sqldialects.xml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  db_queries/.project
  server/src/main/java/com/avengers/yoribogo/recipeboard/controller/RecipeBoardCommentController.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/controller/RecipeBoardReCommentController.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/domain/RecipeBoardComment.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/domain/RecipeBoardCommentStatus.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/domain/RecipeBoardReComment.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/domain/RecipeBoardReCommentStatus.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/dto/RecipeBoardCommentDTO.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/dto/RecipeBoardReCommentDTO.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/repository/RecipeBoardCommentRepository.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/repository/RecipeBoardReCommentRepository.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardCommentService.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardCommentServiceImpl.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardReCommentService.java
Labels: enhancement

#89 Fix: 페이지네이션 오류 수정
  client/src/components/PaginationComponent.vue
  client/src/views/WikiView.vue
Labels: bug, enhancement

#91 Feat: 나만의 레시피 수정
  server/src/main/java/com/avengers/yoribogo/recipeboard/controller/RecipeBoardController.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/controller/RecipeBoardManualController.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/domain/RecipeBoard.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/domain/RecipeBoardManual.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/dto/RecipeBoardDTO.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/dto/ResponseBoardDTO.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/repository/RecipeBoardManualRepository.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardManualService.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardManualServiceImpl.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardService.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardServiceImpl.java
Labels: enhancement

#93 Feat: 나만의 레시피 삭제
  server/src/main/java/com/avengers/yoribogo/recipeboard/controller/RecipeBoardController.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/repository/RecipeBoardRepository.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardService.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardServiceImpl.java
Labels: enhancement

#94 Fix: 요리 추천하기 메뉴 이름 관련 버그 해결
  .idea/.gitignore
  .idea/Yoribogo.iml
  .idea/compiler.xml
  .idea/dataSources.xml
  .idea/gradle.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/sqldialects.xml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  client/src/components/ResultBoard.vue
  client/src/views/ResultView.vue
  client/src/views/WikiDetailView.vue
  server/src/main/java/com/avengers/yoribogo/recipe/service/AIRecipeServiceImpl.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/PublicDataRecipeServiceImpl.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeManualServiceImpl.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeServiceImpl.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecommendedMenuServiceImpl.java
Labels: bug, enhancement

#97 Fix: 추천 요리 이름 안나오는 버그 해결
  client/src/assets/main.css
  client/src/views/HomeView.vue
  client/src/views/ResultView.vue
  client/src/views/WikiDetailView.vue
  server/src/main/java/com/avengers/yoribogo/recipe/service/AIRecipeServiceImpl.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/PublicDataRecipeServiceImpl.java
Labels: bug, enhancement

#99 Refactor: 시맨틱태그 추가
  client/src/components/common/BackButton.vue
  client/src/components/common/GoTopButton.vue
  client/src/components/common/HomeButton.vue
  client/src/components/common/HomeNav.vue
  client/src/components/common/LoadingSpinner.vue
  client/src/components/common/MainBoard.vue
  client/src/components/common/MenuTab.vue
  client/src/components/common/PaginationComponent.vue
  client/src/components/common/ProfileButton.vue
  client/src/components/common/SearchBar.vue
  client/src/components/recipe/MenuItem.vue
  client/src/components/recipe/RecipeManual.vue
  client/src/components/recommend/ChoiceBoard.vue
  client/src/components/recommend/QuestionNav.vue
  client/src/components/recommend/ResultBoard.vue
  client/src/components/recommend/ResultNav.vue
  client/src/views/HomeView.vue
  client/src/views/MyPageView.vue
  client/src/views/QuestionView.vue
  client/src/views/RecipeBoardView.vue
  client/src/views/ResultView.vue
  client/src/views/WikiDetailView.vue
  client/src/views/WikiView.vue
Labels: enhancement

#96 Test: inquiry, answer 기능 및 테스트 코드 수정
  server/src/main/java/com/avengers/yoribogo/answer/controller/AnswerController.java
  server/src/main/java/com/avengers/yoribogo/answer/service/AnswerService.java
  server/src/main/java/com/avengers/yoribogo/answer/service/AnswerServiceImpl.java
  server/src/main/java/com/avengers/yoribogo/common/Status.java
  server/src/main/java/com/avengers/yoribogo/common/Visibility.java
  server/src/main/java/com/avengers/yoribogo/inquiry/controller/InquiryController.java
  server/src/main/java/com/avengers/yoribogo/inquiry/domain/Inquiry.java
  server/src/main/java/com/avengers/yoribogo/inquiry/dto/InquiryDTO.java
  server/src/main/java/com/avengers/yoribogo/inquiry/dto/InquiryOnlyDTO.java
  server/src/main/java/com/avengers/yoribogo/inquiry/service/InquiryService.java
  server/src/main/java/com/avengers/yoribogo/inquiry/service/InquiryServiceImpl.java
  server/src/main/java/com/avengers/yoribogo/mainquestion/service/MainQuestionServiceImpl.java
  server/src/test/java/com/avengers/yoribogo/answer/AnswerTests.java
  server/src/test/java/com/avengers/yoribogo/inquiry/InquiryTests.java
Labels: enhancement

#102 Fix: 로그인 모달 z-index 수정
  client/src/components/top_nav/HomeButton.vue
  client/src/components/user/HomeNav.vue
  client/src/components/user/login/AccountReactivationModal.vue
  client/src/components/user/login/LoginModal.vue
  client/src/components/user/sns/KakaoCallback.vue
  client/src/components/user/sns/NaverCallback.vue
  client/src/components/user/sns/ProfileOAuthModal.vue
  client/src/router/router.js
  client/src/views/HomeView.vue
  client/src/views/MyPageView.vue
  client/src/views/QuestionView.vue
  client/src/views/RecipeBoardView.vue
  client/src/views/ResultView.vue
  client/src/views/WikiView.vue
Labels: bug, enhancement

#103 Fix: import 오류 수정
  client/src/assets/main.css
  client/src/components/recipe/MenuItem.vue
  client/src/components/recipe/RecipeManual.vue
  client/src/views/MyPageView.vue
  client/src/views/WikiDetailView.vue
Labels: bug, enhancement

#105 일반 회원가입 API 추가
  client/src/api/user.js
  client/src/components/user/sns/KakaoCallback.vue
  client/src/components/user/sns/NaverCallback.vue
  client/src/stores/tokenStore.js
  db_queries/integrated_data_insert.sql
  server/.gitignore
  server/src/main/java/com/avengers/yoribogo/security/AuthenticationFilter.java
  server/src/main/java/com/avengers/yoribogo/security/JwtUtil.java
  server/src/main/java/com/avengers/yoribogo/security/WebSecurity.java
  server/src/main/java/com/avengers/yoribogo/user/controller/UserController.java
  server/src/main/java/com/avengers/yoribogo/user/domain/UserEntity.java
  server/src/main/java/com/avengers/yoribogo/user/domain/enums/SignupPath.java
  server/src/main/java/com/avengers/yoribogo/user/domain/vo/ResponseUserVO.java
  server/src/main/java/com/avengers/yoribogo/user/domain/vo/login/AuthTokens.java
  server/src/main/java/com/avengers/yoribogo/user/domain/vo/login/RequestLoginVO.java
  server/src/main/java/com/avengers/yoribogo/user/domain/vo/login/ResponseNormalLoginVO.java
  server/src/main/java/com/avengers/yoribogo/user/domain/vo/login/ResponseOAuthLoginVO.java
  server/src/main/java/com/avengers/yoribogo/user/domain/vo/login/TokenRefreshRequest.java
  server/src/main/java/com/avengers/yoribogo/user/domain/vo/signup/RequestResistEnterpriseUserVO.java
  server/src/main/java/com/avengers/yoribogo/user/dto/UserDTO.java
  server/src/main/java/com/avengers/yoribogo/user/repository/UserRepository.java
  server/src/main/java/com/avengers/yoribogo/user/service/OAuth2LoginService.java
  server/src/main/java/com/avengers/yoribogo/user/service/UserService.java
  server/src/test/java/com/avengers/yoribogo/security/JwtUtilTest.java
  yoribogo_used_images/default_profile.png
Labels: enhancement

#108 Perf: 요리 추천하기 로직 개선
  client/src/components/recommend/ResultBoard.vue
  server/src/main/java/com/avengers/yoribogo/recipe/repository/RecipeRepository.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeServiceImpl.java
Labels: enhancement

#107 Feat: 아이디,닉네임 중복 검증 api 추가
  server/src/main/java/com/avengers/yoribogo/user/controller/UserController.java
  server/src/main/java/com/avengers/yoribogo/user/dto/validate/BooleanResponseDTO.java
  server/src/main/java/com/avengers/yoribogo/user/dto/validate/RequestNicknameDTO.java
  server/src/main/java/com/avengers/yoribogo/user/dto/validate/RequestUserAuthIdDTO.java
  server/src/main/java/com/avengers/yoribogo/user/dto/validate/RequestUserAuthIdentifierDTO.java
  server/src/main/java/com/avengers/yoribogo/user/repository/UserRepository.java
  server/src/main/java/com/avengers/yoribogo/user/service/OAuth2LoginService.java
  server/src/main/java/com/avengers/yoribogo/user/service/UserService.java
Labels: enhancement

#109 Fix: 추천 로직 버그 수정
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeServiceImpl.java
Labels: bug, enhancement

#110 회원탈퇴 및 재활성화 API 추가
  server/src/main/java/com/avengers/yoribogo/user/controller/UserController.java
  server/src/main/java/com/avengers/yoribogo/user/service/UserService.java
Labels: enhancement

#111 Feat: 비밀번호 찾기, 비밀번호 재설정 api 추가
  server/src/main/java/com/avengers/yoribogo/user/controller/UserController.java
  server/src/main/java/com/avengers/yoribogo/user/domain/vo/password/RequestUpdateLoggedInPasswordVO.java
  server/src/main/java/com/avengers/yoribogo/user/domain/vo/password/RequestUpdatePasswordUserVO.java
  server/src/main/java/com/avengers/yoribogo/user/service/UserService.java
Labels: enhancement

#112 Feat: 알림 버튼 구현
  client/src/components/common/NotificationButton.vue
  client/src/views/MyPageView.vue
  client/src/views/QnAview.vue
  client/src/views/RecipeBoardView.vue
  client/src/views/WikiView.vue
Labels: enhancement

#114 Feat: 사용자 프로필 수정 api 추가
  server/src/main/java/com/avengers/yoribogo/user/controller/UserController.java
  server/src/main/java/com/avengers/yoribogo/user/dto/profile/RequestUpdateUserDTO.java
  server/src/main/java/com/avengers/yoribogo/user/service/UserService.java
Labels: enhancement

#115 관리자 회원가입 기능 추가
  server/src/main/java/com/avengers/yoribogo/user/controller/UserController.java
  server/src/main/java/com/avengers/yoribogo/user/domain/vo/signup/RequestResistAdminUserVO.java
  server/src/main/java/com/avengers/yoribogo/user/service/UserService.java
  yoribogo_used_images/admin_default_profile.png
Labels: enhancement

#118 Feat: AI 요리 사진 생성 기능 추가
  client/src/components/common/NotificationButton.vue
  db_queries/table_definition.sql
  server/src/main/java/com/avengers/yoribogo/openai/aggregate/ImageData.java
  server/src/main/java/com/avengers/yoribogo/openai/dto/RequestImagesDTO.java
  server/src/main/java/com/avengers/yoribogo/openai/dto/ResponseImagesDTO.java
  server/src/main/java/com/avengers/yoribogo/openai/service/OpenAIService.java
  server/src/main/java/com/avengers/yoribogo/openai/service/OpenAIServiceImpl.java
  server/src/main/java/com/avengers/yoribogo/recipe/domain/AIRecipe.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/AIRecipeServiceImpl.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeService.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeServiceImpl.java
Labels: enhancement

#122 Feat: s3 테스트 코드 추가 및 userId로 사용자 정보 조회 기능 추가
  client/src/api/user.js
  server/build.gradle
  server/src/main/java/com/avengers/yoribogo/user/controller/UserController.java
  server/src/main/java/com/avengers/yoribogo/user/repository/UserRepository.java
  server/src/main/java/com/avengers/yoribogo/user/service/UserService.java
  server/src/test/java/com/avengers/yoribogo/user/service/UserServiceTest.java
  server/src/test/resources/static/image/default-profile.png
Labels: enhancement

#120 Feat: QnA목록 구현
  client/src/assets/images/private_icon.png
  client/src/assets/images/search_icon.png
  client/src/router/router.js
  client/src/views/InquiryView.vue
Labels: enhancement

#123 Refactor: UserEntity와 Tier 테이블 연관관계 매핑
  db_queries/integrated_data_insert.sql
  server/src/main/java/com/avengers/yoribogo/user/controller/UserController.java
  server/src/main/java/com/avengers/yoribogo/user/domain/Tier.java
  server/src/main/java/com/avengers/yoribogo/user/domain/UserEntity.java
  server/src/main/java/com/avengers/yoribogo/user/dto/profile/ResponseUserProfileDTO.java
  server/src/main/java/com/avengers/yoribogo/user/repository/TierRepository.java
  server/src/main/java/com/avengers/yoribogo/user/repository/UserRepository.java
  server/src/main/java/com/avengers/yoribogo/user/service/OAuth2LoginService.java
  server/src/main/java/com/avengers/yoribogo/user/service/UserService.java
  server/src/test/java/com/avengers/yoribogo/user/service/UserServiceTest.java
Labels: enhancement

#126 Feat: 즐겨찾기 상태값 반환 로직 추가
  server/src/main/java/com/avengers/yoribogo/recipeboard/controller/RecipeBoardFavoriteController.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/dto/FavoriteStatusDTO.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardFavoriteService.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardFavoriteServiceImpl.java
Labels: enhancement

#124 Feat: 요리 사진 S3 업로드 및 불러오기 구현
  server/src/main/java/com/avengers/yoribogo/config/S3Config.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeServiceImpl.java
Labels: enhancement

#127 Test: JwtUtil 테스트 코드 추가
  server/src/main/java/com/avengers/yoribogo/security/JwtUtil.java
  server/src/test/java/com/avengers/yoribogo/security/JwtUtilTest.java
  server/src/test/java/com/avengers/yoribogo/user/service/UserServiceTest.java
Labels: enhancement

#134 Feat: 만족도 조사 구현
  client/src/assets/main.css
  client/src/views/HomeView.vue
  client/src/views/ResultView.vue
  server/src/main/java/com/avengers/yoribogo/openai/service/OpenAIServiceImpl.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeServiceImpl.java
Labels: enhancement

#136 Add: 컴포넌트 추가
  client/src/components/recommend/ResponseBoard.vue
Labels: enhancement

#137 Fix: client의 Qna/QnaDetail 페이지 수정, server의 Inquiry/Answer 서비스 및 테스트 코드 수정
  client/src/api/qna.js
  client/src/assets/images/answer_icon.png
  client/src/assets/images/inquiry_icon.png
  client/src/router/router.js
  client/src/views/InquiryView.vue
  client/src/views/QnAview.vue
  client/src/views/QnaDetailView.vue
  server/src/main/java/com/avengers/yoribogo/answer/controller/AnswerController.java
  server/src/main/java/com/avengers/yoribogo/answer/domain/Answer.java
  server/src/main/java/com/avengers/yoribogo/answer/dto/AnswerDTO.java
  server/src/main/java/com/avengers/yoribogo/answer/service/AnswerServiceImpl.java
  server/src/main/java/com/avengers/yoribogo/inquiry/controller/InquiryController.java
  server/src/main/java/com/avengers/yoribogo/inquiry/domain/Inquiry.java
  server/src/main/java/com/avengers/yoribogo/inquiry/dto/InquiryDTO.java
  server/src/main/java/com/avengers/yoribogo/inquiry/dto/InquiryOnlyDTO.java
  server/src/main/java/com/avengers/yoribogo/inquiry/service/InquiryServiceImpl.java
  server/src/test/java/com/avengers/yoribogo/answer/AnswerTests.java
  server/src/test/java/com/avengers/yoribogo/inquiry/InquiryTests.java
Labels: enhancement

#138 Feat: 회원가입, 로그인 페이지 생성완료
  client/src/api/user.js
  client/src/assets/images/basic_profile.png
  client/src/components/common/ProfileButton.vue
  client/src/components/user/HomeNav.vue
  client/src/components/user/login/LoginModal.vue
  client/src/router/router.js
  client/src/stores/tokenStore.js
  client/src/views/user/LoginView.vue
  client/src/views/user/SignupView.vue
  yoribogo_used_images/basic_profile.png
Labels: enhancement

#140 Feat: 나만의 레시피 작성 페이지 일부 구현
  client/src/assets/main.css
  client/src/components/common/SearchBar.vue
  client/src/components/recipe-board/AtrributeImageInput.vue
  client/src/components/recipe-board/AtrributeTextAndImageInput.vue
  client/src/components/recipe-board/AttributeTextInput.vue
  client/src/components/recipe-board/WriteRecipeBoardComponent.vue
  client/src/views/RecipeBoardView.vue
Labels: enhancement

#141 Refactor: Insert문 추가
  db_queries/integrated_data_insert.sql
Labels: enhancement

#143 Refactor: 나만의 레시피 s3 업로드 관련 리팩터 및 로직 수정
  server/src/main/java/com/avengers/yoribogo/recipeboard/controller/RecipeBoardController.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/dto/RecipeBoardDTO.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/dto/RecipeBoardManualDTO.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/repository/RecipeBoardManualRepository.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardService.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardServiceImpl.java
Labels: enhancement

#144 Perf: 프롬프트 개선
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeServiceImpl.java
Labels: enhancement

#147 충돌해결
  client/src/api/user.js
  client/src/assets/images/login_page_profile.png
  client/src/components/common/HomeNav.vue
  client/src/components/user/HomeNav.vue
  client/src/components/user/login/FindIdStep1.vue
  client/src/components/user/login/FindIdStep2.vue
  client/src/components/user/login/LoginModal.vue
  client/src/components/user/login/PasswordResetStep1.vue
  client/src/components/user/login/PasswordResetStep2.vue
  client/src/components/user/login/PrivacyPolicyModal.vue
  client/src/stores/tokenStore.js
  client/src/views/user/LoginView.vue
  client/vite.config.js
  db_queries/integrated_data_insert.sql
  server/src/main/java/com/avengers/yoribogo/config/WebConfig.java
  server/src/main/java/com/avengers/yoribogo/notification/weeklypopularrecipe/service/WeeklyPopularRecipeService.java
  yoribogo_used_images/login_page_profile.png
Labels: enhancement

#148 아이디 찾기 세부창
  client/src/api/axios.js
  client/src/api/user.js
  client/src/components/common/YesNoButton.vue
  client/src/components/user/login/FindIdStep1.vue
  client/src/components/user/login/FindIdStep2.vue
  server/src/main/java/com/avengers/yoribogo/user/controller/UserController.java
  server/src/main/java/com/avengers/yoribogo/user/domain/vo/UserIdEmailVerificationVO.java
  server/src/main/java/com/avengers/yoribogo/user/service/EmailVerificationService.java
Labels: enhancement

#149 Fix: 호날두 출력 방지
  client/src/views/ResultView.vue
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeServiceImpl.java
Labels: bug, enhancement

#151 비밀번호 찾기 세부창, 재활성화 기능 추가
  client/src/api/user.js
  client/src/components/user/login/AccountReactivationModal.vue
  client/src/components/user/login/FindIdStep1.vue
  client/src/components/user/login/PasswordResetStep1.vue
  client/src/components/user/login/PasswordResetStep2.vue
  client/src/views/user/LoginView.vue
  server/src/main/java/com/avengers/yoribogo/user/service/UserService.java
Labels: enhancement

#152 Refactor: 메뉴 이름 나오는 길이 수정
  client/src/components/recommend/ResultBoard.vue
Labels: enhancement

#153 Feat: 회원가입 세부창 추가
  client/src/components/user/login/FindIdStep1.vue
  client/src/components/user/login/FindIdStep2.vue
  client/src/components/user/login/LoginModal.vue
  client/src/components/user/login/PasswordResetStep1.vue
  client/src/components/user/login/PasswordResetStep2.vue
  client/src/components/user/signup/PrivacyPolicyModal.vue
  client/src/components/user/signup/SignupStep1.vue
  client/src/components/user/signup/SignupStep2.vue
  client/src/views/user/LoginView.vue
  client/src/views/user/SignupView.vue
Labels: enhancement

#154 Feat: 마이페이지에 프로필 사진 추가
  client/src/api/user.js
  client/src/components/user/profile/UserProfile.vue
  client/src/views/MyPageView.vue
  server/src/main/java/com/avengers/yoribogo/user/controller/UserController.java
  server/src/main/java/com/avengers/yoribogo/user/dto/profile/ResponseUserProfileDTO.java
Labels: enhancement

#155 Feat: 문의/답변 기능 구현
  client/src/api/qna.js
  client/src/assets/images/kebab_menu_icon.png
  client/src/router/router.js
  client/src/views/QnAview.vue
  client/src/views/QnaCreateView.vue
  client/src/views/QnaDetailView.vue
  client/src/views/QnaEditView.vue
  server/src/main/java/com/avengers/yoribogo/answer/controller/AnswerController.java
  server/src/main/java/com/avengers/yoribogo/answer/dto/AnswerDTO.java
  server/src/main/java/com/avengers/yoribogo/answer/service/AnswerServiceImpl.java
  server/src/main/java/com/avengers/yoribogo/inquiry/domain/Inquiry.java
  server/src/main/java/com/avengers/yoribogo/inquiry/dto/InquiryDTO.java
  server/src/main/java/com/avengers/yoribogo/inquiry/service/InquiryServiceImpl.java
  server/src/test/java/com/avengers/yoribogo/answer/AnswerTests.java
  server/src/test/java/com/avengers/yoribogo/inquiry/InquiryTests.java
Labels: enhancement

#156 Feat: 마이페이지 틀 세팅 완료
  client/src/components/mypage/BookmarkedRecipes.vue
  client/src/components/mypage/MyRecipes.vue
  client/src/components/mypage/SatisfiedRecipes.vue
  client/src/components/user/profile/ProfileEditModal.vue
  client/src/components/user/profile/UserProfile.vue
  client/src/views/MyPageView.vue
Labels: enhancement

#157 Fix: 문의 게시판 글씨 크기 수정, 답변 삭제 버튼 수정
  client/src/views/QnAview.vue
  client/src/views/QnaDetailView.vue
Labels: enhancement

#162 회원정보 수정 모달창 기본틀 세팅 및 비밀번호 세부창 기능 추가
  client/src/components/user/profile/AccountDeactivationModal.vue
  client/src/components/user/profile/AccountOptionsModal.vue
  client/src/components/user/profile/ChangePasswordModal.vue
  client/src/components/user/profile/ProfileEditModal.vue
  client/src/components/user/profile/UserProfile.vue
  client/src/views/MyPageView.vue
Labels: enhancement

#163 Feat: 사용자 프로필 정보 세부창 및 회원 탈퇴 세부창 추가
  client/src/components/user/profile/AccountDeactivationModal.vue
  client/src/components/user/profile/AccountOptionsModal.vue
  client/src/components/user/profile/ProfileEditModal.vue
  client/src/components/user/signup/SignupStep1.vue
  client/src/views/MyPageView.vue
Labels: enhancement

#164 Refactor: 로그인 안한 사용자는 만족도 조사가 안보이게 수정
  client/src/components/common/ProfileButton.vue
  client/src/components/user/profile/ProfileEditModal.vue
  client/src/components/user/profile/UserProfile.vue
  client/src/components/user/sns/ProfileOAuthModal.vue
  client/src/views/ResultView.vue
Labels: enhancement

#165 Feat: 카카오 로그인, 네이버 로그인 완료
  client/src/components/user/profile/AccountOptionsModal.vue
  client/src/components/user/profile/UserProfile.vue
  client/src/components/user/sns/KakaoCallback.vue
  client/src/components/user/sns/NaverCallback.vue
  client/src/components/user/sns/ProfileOAuthModal.vue
Labels: enhancement

#166 Refactor: 문의 답변 헤더 추가
  client/src/components/user/profile/AccountOptionsModal.vue
  client/src/views/QnAview.vue
  client/src/views/QnaCreateView.vue
  client/src/views/QnaDetailView.vue
  client/src/views/QnaEditView.vue
  client/src/views/QuestionView.vue
  yoribogo_used_images/recipe_986.png
Labels: enhancement

#167 Feat: 나만의 레시피 상세조회 페이지 화면 구현
  client/src/router/router.js
  client/src/views/RecipeBoardDetailView.vue
Labels: enhancement

#168 Fix: inquiry.userId -> inquiry.user.userId로 변경
  client/src/views/QnAview.vue
Labels: enhancement

#169 회원가입 step1, 비밀번호 step1 수정
  client/src/components/user/login/PasswordResetStep1.vue
  client/src/components/user/signup/SignupStep1.vue
  client/src/components/user/signup/SignupStep2.vue
  client/src/stores/tokenStore.js
  client/src/views/QnAview.vue
  client/src/views/QnaDetailView.vue
  server/src/main/java/com/avengers/yoribogo/user/service/EmailVerificationService.java
Labels: enhancement

#171 Feat: 마이페이지 기본 UI 추가
  client/src/assets/main.css
  client/src/components/common/MainBoard.vue
  client/src/components/mypage/BookmarkedRecipes.vue
  client/src/components/mypage/MyRecipes.vue
  client/src/components/mypage/SatisfiedRecipes.vue
  client/src/components/user/profile/UserProfile.vue
  client/src/views/MyPageView.vue
Labels: enhancement

#172 Refactor: 만족한 요리 페이지네이션 추가
  client/src/views/MyPageView.vue
  server/src/main/java/com/avengers/yoribogo/recipe/controller/RecommendedMenuController.java
  server/src/main/java/com/avengers/yoribogo/recipe/repository/RecommendedMenuRepository.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecommendedMenuService.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecommendedMenuServiceImpl.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardFavoriteServiceImpl.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardServiceImpl.java
  server/src/test/java/com/avengers/yoribogo/recipe/service/RecommendedMenuServiceTests.java
Labels: enhancement

#173 Feat: 나만의 레시피 게시글 전체 조회 및 상세 조회와 연결
  client/src/router/router.js
  client/src/views/RecipeBoardDetailView.vue
  client/src/views/RecipeBoardListView.vue
  server/src/main/java/com/avengers/yoribogo/recipeboard/dto/RecipeBoardDTO.java
Labels: enhancement

#174 Feat: 마이페이지 페이지네이션 일부구현
  client/src/router/router.js
  client/src/views/MyPageView.vue
Labels: enhancement

#175 Fix: 라우터 수정, Tab 버그 수정
  client/src/components/recipe-board/AtrributeImageInput.vue
  client/src/components/recipe-board/AtrributeTextAndImageInput.vue
  client/src/components/recipe-board/AttributeIngredientInput.vue
  client/src/components/recipe-board/AttributeIngredientStep.vue
  client/src/components/recipe-board/AttributeMenuNameInput.vue
  client/src/components/recipe-board/RecipeListView.vue
  client/src/components/recipe-board/RecipeViewSwitchButton.vue
  client/src/components/recipe-board/WriteRecipeBoardComponent.vue
  client/src/components/recipe-board/WriteRecipeButton.vue
  client/src/components/recipe-board/WriteRecipeInput.vue
  client/src/components/recipe-board/WriteRecipeView.vue
  client/src/components/recipe-board/WriteStepInput.vue
  client/src/router/router.js
  client/src/views/RecipeBoardListView.vue
  client/src/views/RecipeBoardView.vue
Labels: bug, enhancement

#176 Feat: 마이페이지 페이지네이션 구현
  client/src/views/MyPageView.vue
Labels: enhancement

#178 Feature/user/server
  client/src/components/common/HomeNav.vue
  client/src/components/common/NotificationButton.vue
  client/src/components/common/NotificationModal.vue
  client/src/components/common/ProfileButton.vue
  client/src/components/user/HomeNav.vue
  client/src/views/HomeView.vue
Labels: enhancement

#179 Fix: 만족 리스트에서 새로고침했을때 북마크가 나오는 버그 수정
  client/src/views/MyPageView.vue
  server/src/main/java/com/avengers/yoribogo/recipe/repository/RecommendedMenuRepository.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecommendedMenuServiceImpl.java
Labels: enhancement

#180 Fix: 테스트 코드 빌드를 위해 주석 처리
  server/src/test/java/com/avengers/yoribogo/inquiry/InquiryTests.java
Labels: bug

#181 Feat: 나만의 레시피 주간, 전체 토글 전환
  client/src/components/recipe-board/RecipeViewSwitchButton.vue
  client/src/views/RecipeBoardListView.vue
Labels: enhancement

#182 Fix: 문의 테스트 코드 수정
  server/src/test/java/com/avengers/yoribogo/inquiry/InquiryTests.java
Labels: enhancement

#183 Style: css 수정
  client/src/components/common/MainBoard.vue
  client/src/views/QnaDetailView.vue
  client/src/views/QnaView.vue
Labels: enhancement

#184 Style: HomeNav css 수정
  client/src/assets/main.css
Labels: enhancement

#186 Feat: 나만의 레시피 댓글 하는중
  client/src/components/recipe-board/AtrributeTextAndImageInput.vue
  client/src/components/recipe-board/WriteCommentInput.vue
  client/src/components/recipe-board/WriteRecommentInput.vue
  client/src/components/recipe-board/WriteStepInput.vue
  client/src/views/RecipeBoardDetailView.vue
  client/src/views/RecipeBoardListView.vue
  server/src/main/java/com/avengers/yoribogo/recipeboard/controller/RecipeBoardCommentController.java
  server/src/main/java/com/avengers/yoribogo/recipeboard/controller/RecipeBoardRecommentController.java
Labels: enhancement

#187 Feat: 나만의 레시피 등록 중간 커밋
  client/src/components/recipe-board/AtrributeTextAndImageInput.vue
  client/src/components/recipe-board/WriteRecipeBoardComponent.vue
Labels: enhancement

#189 Feat: 나만의 레시피 댓글 작성 구현
  client/src/components/recipe-board/WriteCommentInput.vue
  client/src/components/recipe-board/WriteRecommentInput.vue
  client/src/router/router.js
  client/src/views/RecipeBoardDetailView.vue
  client/src/views/RecipeBoardListView.vue
  client/src/views/RecipeBoardWriteView.vue
Labels: enhancement

#190 Refactor: 프로필 둥글게 나오게 수정
  client/src/components/recipe-board/WriteCommentInput.vue
  client/src/views/RecipeBoardDetailView.vue
Labels: enhancement

#192 Style: CSS 수정
  client/src/components/recipe-board/WriteCommentInput.vue
Labels: enhancement

#193 Fix: 즐겨찾기 버튼 제거
  client/src/views/RecipeBoardDetailView.vue
Labels: enhancement

#194 Style: 글쓰기 버튼 위치 변경
  client/src/components/recipe-board/RecipeListView.vue
  client/src/views/RecipeBoardDetailView.vue
  client/src/views/RecipeBoardListView.vue
Labels: enhancement

#195 Fix: 검색 기능 수정
  client/src/views/RecipeBoardListView.vue
Labels: bug, enhancement

#196 Refactor: JsonProperty 수정
  server/src/main/java/com/avengers/yoribogo/recipeboard/dto/RecipeBoardCommentDTO.java
Labels: enhancement

#197 Feat: 나만의 레시피 등록 완
  client/src/components/recipe-board/AtrributeImageInput.vue
  client/src/components/recipe-board/AtrributeTextAndImageInput.vue
  client/src/components/recipe-board/AttributeIngredientStep.vue
  client/src/components/recipe-board/AttributeMenuNameInput.vue
  client/src/components/recipe-board/WriteRecipeBoardComponent.vue
  client/src/components/recipe-board/WriteStepInput.vue
  client/src/stores/tokenStore.js
  client/src/views/RecipeBoardListView.vue
  client/src/views/RecipeBoardWriteView.vue
Labels: enhancement

#198 Feat: 레시피 보드에서 탭 제거
  client/src/components/recipe-board/WriteRecipeBoardComponent.vue
  client/src/router/router.js
  client/src/views/RecipeBoardDetailView.vue
  client/src/views/RecipeBoardListView.vue
  client/src/views/RecipeBoardWriteView.vue
Labels: enhancement

#199 Refactor: 추천화면에서 알림 삭제
  client/src/views/QuestionView.vue
  client/src/views/RecipeBoardListView.vue
Labels: enhancement

#201 Feat: 나만의 레시피 페이지에 알림버튼 추가
  client/src/views/RecipeBoardDetailView.vue
  client/src/views/RecipeBoardListView.vue
Labels: enhancement

#202 Feat: 요리 상세페이지 알림 버튼 추가
  client/src/views/WikiDetailView.vue
Labels: enhancement

#203 알림 기능 추가
  client/package-lock.json
  client/package.json
  client/src/App.vue
  client/src/api/SSERequest.js
  client/src/api/userNotification.js
  client/src/components/common/NotificationButton.vue
  client/src/components/common/NotificationModal.vue
  client/src/views/HomeView.vue
  server/src/main/java/com/avengers/yoribogo/config/CorsConfig.java
  server/src/main/java/com/avengers/yoribogo/config/MongoDBConfig.java
  server/src/main/java/com/avengers/yoribogo/notification/notification/contoller/NotificationController.java
  server/src/main/java/com/avengers/yoribogo/notification/notification/domain/NotificationEntity.java
  server/src/main/java/com/avengers/yoribogo/notification/notification/domain/NotificationScheduler.java
  server/src/main/java/com/avengers/yoribogo/notification/notification/domain/NotificationStatus.java
  server/src/main/java/com/avengers/yoribogo/notification/notification/dto/NotificationDTO.java
  server/src/main/java/com/avengers/yoribogo/notification/notification/dto/NotificationStatus.java
  server/src/main/java/com/avengers/yoribogo/notification/notification/dto/NotificationStatusUpdateRequestDTO.java
  server/src/main/java/com/avengers/yoribogo/notification/notification/repository/NotificationRepository.java
  server/src/main/java/com/avengers/yoribogo/notification/notification/service/NotificationScheduler.java
  server/src/main/java/com/avengers/yoribogo/notification/notification/service/NotificationService.java
  server/src/main/java/com/avengers/yoribogo/notification/weeklypopularrecipe/controller/WeeklyPopularRecipeController.java
  server/src/main/java/com/avengers/yoribogo/notification/weeklypopularrecipe/dto/WeeklyPopularRecipeEntity.java
  server/src/main/java/com/avengers/yoribogo/notification/weeklypopularrecipe/repository/WeeklyPopularRecipeMongoRepository.java
  server/src/main/java/com/avengers/yoribogo/notification/weeklypopularrecipe/service/WeeklyPopularRecipeService.java
  server/src/main/java/com/avengers/yoribogo/security/JwtUtil.java
  server/src/main/java/com/avengers/yoribogo/security/WebSecurity.java
  server/src/main/java/com/avengers/yoribogo/user/repository/UserRepository.java
Labels: enhancement

#204 Refactor: 알림 테이블 수정
  db_queries/table_definition.sql
Labels: enhancement

#205 Perf: 요리 추천 사진 생성 비동기 설정
  server/src/main/java/com/avengers/yoribogo/ServerApplication.java
  server/src/main/java/com/avengers/yoribogo/config/AsyncConfig.java
  server/src/main/java/com/avengers/yoribogo/notification/notification/service/NotificationScheduler.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/ImageService.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/ImageServiceImpl.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeService.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeServiceImpl.java
Labels: enhancement

#206 Fix: 로그아웃 버그 수정
  client/src/components/common/ProfileButton.vue
Labels: bug, enhancement

#208 Perf: 요리 추천 매뉴얼 생성 비동기 처리
  client/src/components/recommend/ResultBoard.vue
  server/src/main/java/com/avengers/yoribogo/recipe/service/ImageService.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/ImageServiceImpl.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeManualService.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeManualServiceImpl.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeServiceImpl.java
Labels: enhancement

#210 Perf: 요리 추천 매뉴얼 생성 WebFlux 처리
  client/src/views/WikiDetailView.vue
  server/build.gradle
  server/src/main/java/com/avengers/yoribogo/openai/dto/RequestChatDTO.java
  server/src/main/java/com/avengers/yoribogo/openai/dto/ResponseChatDTO.java
  server/src/main/java/com/avengers/yoribogo/openai/dto/ResponseChatFluxDTO.java
  server/src/main/java/com/avengers/yoribogo/openai/provider/OpenAIProvider.java
  server/src/main/java/com/avengers/yoribogo/openai/service/OpenAIService.java
  server/src/main/java/com/avengers/yoribogo/openai/service/OpenAIServiceImpl.java
  server/src/main/java/com/avengers/yoribogo/recipe/controller/RecipeManualController.java
  server/src/main/java/com/avengers/yoribogo/recipe/dto/RequestAIRecipeManualDTO.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeManualService.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeManualServiceImpl.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeServiceImpl.java
Labels: enhancement

#212 Perf: sse를 통한 요리사진 리렌더링
  client/src/components/recommend/ResultBoard.vue
  client/src/views/WikiDetailView.vue
  server/src/main/java/com/avengers/yoribogo/notification/notification/service/NotificationService.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/ImageServiceImpl.java
Labels: enhancement

#213 Refactor: 정규표현식 수정
  client/src/views/MyPageView.vue
  client/src/views/QnaCreateView.vue
  client/src/views/QnaDetailView.vue
  client/src/views/QnaEditView.vue
  client/src/views/QnaView.vue
  client/src/views/RecipeBoardDetailView.vue
  client/src/views/RecipeBoardListView.vue
  client/src/views/RecipeBoardWriteView.vue
  client/src/views/ResultView.vue
  client/src/views/WikiDetailView.vue
  client/src/views/WikiView.vue
Labels: enhancement

#214 Fix: SSE 에러 수정
  client/src/App.vue
  client/src/api/SSERequest.js
  client/src/api/like.js
  client/src/api/qna.js
  client/src/components/common/MainBoard.vue
  client/src/components/common/MenuTab.vue
  client/src/components/common/NotificationButton.vue
  client/src/components/common/NotificationModal.vue
  client/src/components/common/ProfileButton.vue
  client/src/components/common/YesNoButton.vue
  client/src/components/mypage/BookmarkedRecipes.vue
  client/src/components/mypage/MyRecipes.vue
  client/src/components/mypage/SatisfiedRecipes.vue
  client/src/components/recipe-board/AtrributeImageInput.vue
  client/src/components/recipe-board/AtrributeTextAndImageInput.vue
  client/src/components/recipe-board/AttributeIngredientInput.vue
  client/src/components/recipe-board/AttributeIngredientStep.vue
  client/src/components/recipe-board/AttributeMenuNameInput.vue
  client/src/components/recipe-board/RecipeViewSwitchButton.vue
  client/src/components/recipe-board/WriteCommentInput.vue
  client/src/components/recipe-board/WriteRecipeBoardComponent.vue
  client/src/components/recipe-board/WriteRecipeButton.vue
  client/src/components/recipe-board/WriteRecipeInput.vue
  client/src/components/recipe-board/WriteRecipeView.vue
  client/src/components/recipe-board/WriteStepInput.vue
  client/src/components/user/HomeNav.vue
  client/src/components/user/login/AccountReactivationModal.vue
  client/src/components/user/login/FindIdStep1.vue
  client/src/components/user/login/FindIdStep2.vue
  client/src/components/user/login/LoginModal.vue
  client/src/components/user/login/PasswordResetStep1.vue
  client/src/components/user/login/PasswordResetStep2.vue
  client/src/components/user/profile/AccountDeactivationModal.vue
  client/src/components/user/profile/ChangePasswordModal.vue
  client/src/components/user/profile/ProfileEditModal.vue
  client/src/components/user/profile/UserProfile.vue
  client/src/components/user/signup/SignupStep1.vue
  client/src/components/user/signup/SignupStep2.vue
  client/src/components/user/sns/KakaoCallback.vue
  client/src/components/user/sns/NaverCallback.vue
  client/src/components/user/sns/ProfileOAuthModal.vue
  client/src/router/router.js
  client/src/stores/tokenStore.js
  client/src/views/HomeView.vue
  client/src/views/MyPageView.vue
  client/src/views/QnaCreateView.vue
  client/src/views/QnaDetailView.vue
  client/src/views/QnaEditView.vue
  client/src/views/QnaView.vue
  client/src/views/RecipeBoardDetailView.vue
  client/src/views/RecipeBoardListView.vue
  client/src/views/RecipeBoardWriteView.vue
  client/src/views/WikiDetailView.vue
  server/src/main/java/com/avengers/yoribogo/notification/notification/service/NotificationService.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeServiceImpl.java
Labels: bug, enhancement

#215 Refactor: 쓰레드 수 조절
  server/src/main/java/com/avengers/yoribogo/config/AsyncConfig.java
  server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeServiceImpl.java
Labels: enhancement

#217 Update README.md
  README.md
Labels: enhancement

#218 Docker,Kubernetes를 통한 배포
  client/Dockerfile
  client/nginx.conf
  client/src/api/SSERequest.js
  client/src/api/axios.js
  client/src/components/common/NotificationButton.vue
  client/src/components/common/ProfileButton.vue
  client/src/components/recipe-board/WriteRecipeBoardComponent.vue
  client/src/components/user/HomeNav.vue
  client/src/components/user/login/LoginModal.vue
  client/src/router/router.js
  client/src/stores/tokenStore.js
  client/src/views/MyPageView.vue
  client/src/views/QnaCreateView.vue
  client/src/views/QnaDetailView.vue
  client/src/views/QnaEditView.vue
  client/src/views/QnaView.vue
  client/src/views/RecipeBoardDetailView.vue
  client/src/views/RecipeBoardListView.vue
  client/src/views/RecipeBoardWriteView.vue
  client/src/views/ResultView.vue
  client/src/views/WikiDetailView.vue
  client/src/views/WikiView.vue
  client/vite.config.js
  db_queries/table_definition.sql
  docker_db_images/mariadb/.gitignore
  docker_db_images/mariadb/Dockerfile
  docker_db_images/mongodb/.gitignore
  docker_db_images/mongodb/Dockerfile
  docker_db_images/redis/.gitignore
  docker_db_images/redis/Dockerfile
  kubernetes_manifests/ingress/ingress002.yml
  kubernetes_manifests/mariadb/.gitignore
  kubernetes_manifests/mariadb/mariadb-secret.yml
  kubernetes_manifests/mariadb/mariadb001dep.yml
  kubernetes_manifests/mariadb/mariadb001ser.yml
  kubernetes_manifests/mongodb/mongodb001dep.yml
  kubernetes_manifests/mongodb/mongodb001ser.yml
  kubernetes_manifests/redis/redis001dep.yml
  kubernetes_manifests/redis/redis001ser.yml
  kubernetes_manifests/spring_boot/boot002dep.yml
  kubernetes_manifests/spring_boot/boot002ser.yml
  kubernetes_manifests/vue/vue002dep.yml
  kubernetes_manifests/vue/vue002ser.yml
  server/Dockerfile
  server/src/main/java/com/avengers/yoribogo/config/CorsConfig.java
  server/src/main/java/com/avengers/yoribogo/config/RedisConfig.java
  server/src/main/java/com/avengers/yoribogo/config/WebConfig.java
  yoribogo_used_images/yoribogo_jenkins_test.gif
Labels: enhancement

#221 Feat: Flux에서 Byte 문자 처리를 위한 StringHttp 추가
  client/nginx.conf
  client/src/api/SSERequest.js
  client/src/components/common/NotificationButton.vue
  client/src/views/WikiDetailView.vue
  docker_db_images/mariadb/Dockerfile
  kubernetes_manifests/ingress/ingress002.yml
  kubernetes_manifests/redis/redis001dep.yml
  server/src/main/java/com/avengers/yoribogo/config/WebConfig.java
  server/src/main/java/com/avengers/yoribogo/recipe/controller/RecipeManualController.java
Labels: enhancement
